package io.github.stumblehome.headless;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.Sprite;
import com.badlogic.gdx.maps.tiled.TiledMap;
import com.badlogic.gdx.maps.tiled.TiledMapTileLayer;
import com.badlogic.gdx.maps.tiled.TmxMapLoader;
import io.github.stumblehome.Player;
import org.junit.jupiter.api.Test;

public class PlayerTest extends AbstractHeadlessGdxTest {

    @Test
    public void testCollisionWithMazeWall() {
        // Load the map
        TiledMap map = new TmxMapLoader().load("map.tmx");

        // Set up map size to be the same as the game
        int mapWidthInTiles = map.getProperties().get("width", Integer.class);
        int mapHeightInTiles = map.getProperties().get("height", Integer.class);
        int tilePixelWidth = map.getProperties().get("tilewidth", Integer.class);
        int tilePixelHeight = map.getProperties().get("tileheight", Integer.class);

        // Calculate map dimensions in world units (remember: 1 world unit = 16 pixels)
        float mapWidth = mapWidthInTiles * tilePixelWidth / 16f;
        float mapHeight = mapHeightInTiles * tilePixelHeight / 16f;

        // Load collision layers
        TiledMapTileLayer collisionLayer = (TiledMapTileLayer) map.getLayers().get("hedge");
        // Create player for test
        Player player =
                new Player(
                        new Sprite(new Texture("character.png")),
                        mapWidth,
                        mapHeight,
                        collisionLayer);

        // Test moving to coords without wall
        assertTrue(player.canMoveTo(1, 1));

        // Tests moving to coords where walls are
        // Numbers generated by colliding with wall on map
        // And printing out the player co-ordinates

        // Base of player collides with top of wall
        assertFalse(player.canMoveTo(58.940044f, 45.36659f));

        // Right side of player collides with left of wall
        assertFalse(player.canMoveTo(60.234566f, 48.22915f));

        // Left side of player collides with right of wall
        assertFalse(player.canMoveTo(53.982384f, 48.22915f));

        // Top side of player collides with bottom of wall
        assertFalse(player.canMoveTo(59.212196f, 42.200703f));
    }
}
