plugins {
  // Applies the foojay-resolver plugin to allow automatic download of JDKs.
  id("org.gradle.toolchains.foojay-resolver-convention") version "0.9.0"
}

// Make `triangle:lib` the main module for this project. Include platform modules so
// the lwjgl3 desktop launcher can run the game.
rootProject.name = 'stumble-home'
include 'lib'

// Explicit project dir for the single library module
project(':lib').projectDir = file('lib')
