plugins {
  // Applies the foojay-resolver plugin to allow automatic download of JDKs.
  id("org.gradle.toolchains.foojay-resolver-convention") version "0.9.0"
}

// Make `triangle:lib` the main module for this project. Include platform modules so
// the lwjgl3 desktop launcher can run the game.
rootProject.name = 'stumble-home'
include 'core', 'lwjgl3', 'StumbleHome:lib'

// Explicit project dirs (keeps structure stable)
project(':StumbleHome:lib').projectDir = file('StumbleHome/lib')
project(':core').projectDir = file('core')
project(':lwjgl3').projectDir = file('lwjgl3')
