# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main", "*" ]
  pull_request:
    branches: [ "main", "*" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] 
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
  
      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
  
      - name: Build with Gradle Wrapper (Unix)
        if: runner.os != 'Windows'
        run: |
          cd StumbleHome
          ./gradlew --no-daemon --stacktrace build jacocoTestReport
  
      - name: Build with Gradle Wrapper (Windows)
        if: runner.os == 'Windows'
        run: |
          cd StumbleHome
          ./gradlew.bat --no-daemon --stacktrace build jacocoTestReport
  
      # OS-specific lib JAR artifact
      - name: Upload library JAR
        uses: actions/upload-artifact@v4
        with:
          name: lib-${{ matrix.os }}.jar
          path: StumbleHome/lib/build/libs/StumbleHome.jar
  
      # OS-specific JaCoCO report
      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report-${{ matrix.os }}
          path: StumbleHome/lib/build/reports/jacoco/test/html
  
      # Only upload ubuntu build checkstyle report
      - name: Upload Checkstyle report
        if: startsWith(matrix.os, 'ubuntu')
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: StumbleHome/lib/build/reports/checkstyle

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
  
    steps:
      - uses: actions/checkout@v4
  
      # download JAR artifact for each OS created by matrix
      # Ubuntu
      - name: Download Ubuntu Build
        uses: actions/download-artifact@v4
        with:
          name: lib-ubuntu-latest.jar
          path: .
  
      - name: Rename Ubuntu Build
        run: mv StumbleHome/lib/build/libs/StumbleHome.jar lib-ubuntu.jar

      # Windows
      - name: Download Windows Build
        uses: actions/download-artifact@v4
        with:
          name: lib-windows-latest.jar
          path: .

      - name: Rename Windows Build
        run: mv StumbleHome/lib/build/libs/StumbleHome.jar lib-windows.jar

      # MacOS
      - name: Download MacOS Build
        uses: actions/download-artifact@v4
        with:
          name: lib-macos-latest.jar
          path: .

      - name: Rename MacOS Build
        run: mv StumbleHome/lib/build/libs/StumbleHome.jar lib-macos.jar

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            lib-ubuntu.jar
            lib-windows.jar
            lib-macos.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
